### ISSUE TITLE
rannts#19

### ISSUE THREAD

**Issue by 9seconds** [hH39797J/python-videos-ru-2018#10]
Нижегородский Python-meetup, закончилась 19 встреча

https://rannts.ru/meetups/19/
17 марта 2018
https://www.youtube.com/playlist?list=PLxVVhpZX_gJfgQjpZ7dN4vgvKi3KgRVkS

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/python-videos-ru-2018#rannts19
