### ISSUE TITLE
PiterPy Meetup #4

### ISSUE THREAD

**Issue by b0g3r** [hH39797J/python-videos-ru-2018#14]
10 апреля
https://www.youtube.com/watch?v=6D6dmun-GS4
https://www.youtube.com/watch?v=4-iEoN5jK-8
https://www.youtube.com/watch?v=pN66VuaKDjk

Вышлю пдфки с презентациями по запросу (t.me/b0g3r, t.me/piterpy_meetup)

**Comment by hH39797J** [comment]
Спасибо.
Добавим.
t.me у меня нет, так что без презентаций.

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/python-videos-ru-2018#piterpy-meetup-4
