### ISSUE TITLE
PyData SPb #1

### ISSUE THREAD

**Issue by b0g3r** [hH39797J/python-videos-ru-2018#15]
Описание события: https://www.meetup.com/PyData-SPb/events/247116233/
Трансляция события: https://www.youtube.com/watch?v=aoin1nl_eSA
Презентации: https://drive.google.com/drive/folders/1LFd8lpEicupPWJO7nF7X-7Z-rIsKoWME

**Comment by hH39797J** [comment]
Спасибо.
Не соответствует тематике "каталога".
