### ISSUE TITLE
Почему не pyvideo.ru?

### ISSUE THREAD

**Issue by axsapronov** [hH39797J/python-videos-ru-2018#6]
Привет.

Было такое начинание http://pyvideo.ru/  (https://github.com/coagulant/pyvideo.ru/)
Может стоит попросить доступ в репозиторий и оживить сайт?

**Comment by hH39797J** [comment]
Добрый день.

Я видел http://pyvideo.ru/ - меня смутили 2 момента:
1) технические ограничения при добавлении видео не с youtube - https://github.com/coagulant/pyvideo.ru/issues/43
2) никому за более чем 2 года этот проект был не нужен и автор даже не нашёл в себе сил хоть что-то ответить - https://github.com/coagulant/pyvideo.ru/issues/49

В данном проекте (моё личное мнение) важна информация, а не платформа.
